import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { Separator } from "@/components/ui/separator";
import "../globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { userService } from "@/service/user.service";
import { redirect } from "next/navigation";
import QueryProvider from "@/provider/query-provider";
import { ThemeProvider } from "@/components/provider/theme-provider";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await userService.getSession();

  if (!data?.user) {
    return redirect("/login");
  }

  const userInfo = {
    role: data.user.role,
    name: data.user.name,
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground transition-colors duration-500`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SidebarProvider>
              <AppSidebar user={userInfo} />
              {/* REMOVED hardcoded bg-[#020617] */}
              <SidebarInset className="bg-background">
                <header className="flex h-16 shrink-0 items-center gap-2 border-b border-border px-6 sticky top-0 z-20 bg-background/80 backdrop-blur-md">
                  {/* Fixed Trigger text color to handle light/dark */}
                  <SidebarTrigger className="-ml-1 text-primary-foreground bg-primary hover:bg-primary/90 rounded-lg transition-colors" />

                  <Separator
                    orientation="vertical"
                    className="mr-2 h-4 bg-border"
                  />

                  <div className="flex flex-col">
                    <h1 className="text-xs font-black text-primary uppercase tracking-[0.2em]">
                      LearnHub {userInfo.role}
                    </h1>
                    <p className="text-[10px] text-muted-foreground font-medium uppercase tracking-tighter">
                      Welcome back, {userInfo.name?.split(" ")[0]}
                    </p>
                  </div>
                </header>
                <main className="flex flex-1 flex-col gap-6 p-6 lg:p-10 transition-colors duration-500">
                  {children}
                </main>
              </SidebarInset>
            </SidebarProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
